// lists.js

export const quotes = [
    "Come after ME because I'm a MAN and I can handle it when you make FUN of how I look, how I act, and how I speak. THIS is America, baby. LET'S GO!",
    "People, I'm NOT locked in on the West Coast. It's just REALLY different out here, and something's OFF. I've just REALLY been off my game. Syke, GET AFTER IT!",
    "My FAVORITE hobbies are WORKING OUT and honestly STUDYING for tests.",
    "Absolutely HAMMERED weights on a SATURDAY. We're getting AFTER IT. LET'S GO. Gotta find a way to get here. 1 of my car, 2 of my horse.",
    "Almost MONDAY, people. Only a FEW more minutes to go back in the office, HAMMERING spreadsheets and SLUGGING waters. LET'S GO!",
    "SHIT my pants like crazy. I'm going AFTER IT all day every day. GOOD PEOPLE.",
    "YO. We are ABSOLUTELY LOCKED IN.",
    "Come after ME because I'm a MAN and I can handle it when you make FUN of how I look, how I act, and how I speak. THIS is America, baby. LET'S GO!",
    "YO. We are ABSOLUTELY LOCKED IN. LET'S GO people.",
    "Fridays are for the HEAVY HITTERS. 1 if by bus, 2 if by train. How are you hitting the office today?",
    "I'm NOT about to be selling out for money. If someone wants a sponsorship, it better be in 1,000,000. I'm NOT on a rookie contract anymore. Send the Pat Mahomes money THIS WAY if you want it.",
    "Crushed 5 BURRITOS with Friday beers, unreal experience and hopefully brings a lot of ENERGY to your day.",
    "MUSIC intro",
    "Some men aren't looking for anything logical, like money. They CAN'T be bought, bullied, reasoned, or negotiated with. Some men just WON'T watch the world become a BETTER PLACE.",
    "The HEAVY HITTERS haven't seen a rise this fast since Conor McGregor launched his career in the garden. But you know what? We've gotta WORK HARD day after day. NO REASON now to get complacent and start thinking that you're too big. LET'S GET AFTER IT. Do the dirty work, people. LET'S GO!",
    "Locked into the ABSOLUTE MESS.",
    "New York City, we're bringing the POSITIVE VIBES and having a summer weekend. Let the HEAVY HITTERS know. You DON'T GO where the puck is, you GO where the puck's gonna be.",
    "The UNITED STATES of America is the GREATEST COUNTRY on Earth. DON'T let anyone tell you otherwise.",
    "HEAVY HITTERS, watch out. Keep shaking your boots because we're COMING wherever you are.",
    "I'd like to take this chance to APOLOGIZE to ABSOLUTELY NOBODY for breaking the Internet. Instead, I'd like to THANK everyone who's supporting me so we spread POSITIVITY. The world needs more of it. LET'S GO!",
    "CHEFED up a bowl of BISON. It's literally got one ingredient, BISON, nothing on it. Cooked to PERFECTION. LET'S GO!",
    "It's a COMPETITIVE WORLD whether people like it or not. I'm gonna do EVERYTHING I can to make sure my team WINS because other people want what we have. ONLY one person's gonna get it. LET'S GO. Win or lose.",
    "Gonna be RESPONSIBLE and rest up and take it easy this FRIDAY NIGHT. We'll be back STRONGER than ever. Just gotta BELIEVE.",
    "I'm ABSOLUTELY LOCKED IN when I'm working from home because I always give my BEST EFFORT and stay focused throughout the day. It's all about being ACCOUNTABLE and doing the right things.",
    "Make sure you're RIGHT, then go ahead.",
    "Why not go the EXTRA MILE every now and then? Because no matter who you are, no matter what you do, you can INSPIRE. Who are you INSPIRING?",
    "I became an OVERNIGHT SENSATION through years of HARD WORK, but I'm gonna stay TRUE to my values because even if I only had a 1,000 followers like I did last month, I would still do the same exact things and GET AFTER IT for the people.",
    "I heard better CHIRPS at the duck pond that I'm seeing in the comment section. Step the game up, people. My friends are getting bored reading them, so LET'S GO. Right now, I've gotta get back to work, little midday walk.",
    "The HATE fuels me, but right now, the hate is aghast. They're looking for a Dunkin' Donuts. They can get some caffeine, get some ENERGY like we have.",
    "I'm NOT an INFLUENCER. I'm a regular person doing my BEST every day and GETTING AFTER IT. LET'S GO.",
    "Will NOT catch me SLACKING TODAY because I'm ABSOLUTELY AMPED UP to get AFTER IT.",
    "YO. LET'S GO. That's what we're talking about. Having some FUN during the WORKDAY all day every day, but it's fun to run the CALCULATIONS too, honestly.",
    "I'm gonna need a big SECOND HALF of the day right here, so it's time to LOCK IN and get it DONE. LET'S GO.",
    "HEAVY HITTERS of America are about to be shaking in their boots seeing that YOUNG PEOPLE are actually motivated to WORK.",
    "I'm still HUNGRY because BIG DOGS gotta eat. People keep saying I'm gonna get lazy or stray away from the visions and values that make me who I am. Listen to me saying, I'm gonna STAY AFTER IT and keep doing good things. LET'S GO. Lock in.",
    "Please continue to SHARE your opinions in the comment section because that's what our FOUNDING FATHERS wanted. Freedom of speech, press, and expression is what makes this country SPECIAL. So whether it's love or hate, I formally invite you to keep sending those messages up to Boston, the birthplace of freedom where a bunch of farmers and rabble rousers like Sam Adams start the GREATEST COUNTRY on Earth.",
    "YO. They are READY. WE are COMING. LET'S GO.",
    "Ultimately, we need everyone's help to continue building the COMMUNITY STRONGER by exemplifying GOOD VALUES and working hard. Why not go the EXTRA MILE every now and then?",
    "When OPPORTUNITY KNOCKS, I answer. It doesn't matter what day of the week it is or where I am I'm gonna FULL SEND that thing. LET'S have a FRIDAY people.",
    "12 HOURS of sleep, it's TIME to RIP AGAIN. PERSEVERANCE.",
    "You all can say and write whatever you want about me, but please be RESPECTFUL to EVERYONE ELSE. We're out here to be people of CHARACTER. LET'S GO.",
    "Okay. It's a SETBACK. It doesn't mean I'm comfortable. It doesn't mean I'm satisfied, but I can choose to have the mindset of I'm gonna have a CRAZY COMEBACK. That's a quote from one of my favorite athletes, Tim Tebow. LET'S GET IT, people.",
    "We're ABSOLUTELY LOCKED IN!",
    "CHANGE is HARD. It doesn't matter who you are. It'll take you by surprise. So I appreciate everyone's patience. I tried to navigate a whole bunch of different things.",
    "NVIDIA may not be able to keep up with the 15,000 percent GROWTH that this account has seen over the past 5 weeks, but I still greatly respect how they're contributing to the AMERICAN ECONOMY.",
    "TIME to LOCK BACK IN.",
    "Every rep counts right now because I'm having a lot of difficulty getting workouts in. Gotta HAMMER these reps then HAMMER those calculations. LET'S GO.",
    "If you look at your job as a 9 to 5, you're already behind the 8 ball. NO SUNDAY SCARIEST, people. LET'S GO.",
    "INSPIRE AMERICA. That's the quote of the week because I wanna say a big THANK YOU to everyone who's been supporting me for years. This last week, we got a lot of traction. We're still on the same routines that we've been going after day after day, year after year. LET'S GO. LET'S GET AFTER IT.",
    "Just a normal dude GETTING AFTER IT on FRIDAY. I'm NOT the fastest. I'm NOT the strongest, but I'm gonna give it EVERYTHING that I have. It's been a long week, lots of hours of work as y'all have been seeing, but I'm gonna FINISH IT STRONG and bring everything together today. HAVE A GREAT WEEKEND, everyone. KEEP those VIBES going.",
    "At least one RISER WORKOUT each week. Had to WIN this one early and start building the health back. ABSOLUTELY BRUTAL one, but just gotta STICK WITH IT. We're gonna make it happen.",
    "I sleep in at least one day a week to balance everything out and make sure that I recover properly. Also, it definitely helps me keep my ENERGY LEVELS up.",
    "I'm about to be absolutely DIALED IN going to this monthly meeting.",
    "HAULING it through an absolute DOWNPOUR right now because we've got work to do today. It's time to be RESPONSIBLE to make things happen, and NOTHING'S gonna stop that.",
    "RUNNING ON FUMES today, but it's TIME to LOCK THE HECK IN and keep this STRUGGLE BUS rolling. One day at a time, LET'S GET IT DONE.",
    "Until the BRAKES GIVE OUT and the WHEELS FALL OFF. LET'S RIDE people.",
    "Locked in for GREATNESS today because it's time to absolutely HAMMER some Excel spreadsheets.",
    "Locked BACK IN for some cross training on the trails. Just woke up and said, hey. TIME to absolutely SEND IT. So LET'S have a SUNDAY, people. MORE GOOD THINGS on deck.",
    "THANK YOU to everyone who has SACRIFICED their lives so that we can chase our DREAMS and have fun here in the UNITED STATES OF AMERICA.",
    "HELP OTHERS do the right thing, enjoy life every day. Those are the 3 core values I live by, and those are the ones that are gonna keep guiding my decisions into the future.",
    "I'm DIVERSIFYING my business pursuits, but I'm still gonna be HAMMERING sell spreadsheets in the cubicles. The corporate dream lives on, so HEAVY HITTERS, watch out.",
    "Nerves through the ROOF this week because like anyone, I deal with a lot of emotions, and I'm just a regular person going through a CRAZY TIME right now.",
    "Whoever lives the TRUTH comes to the light so that their work may be seen. It's on TOMORROW, people.",
    "Rabble Rowser is about to get the CUBICLES absolutely FIRED UP, causing mayhem every day and CHANGING OFFICE CULTURE across America. LET'S GO.",
    "Back on the REGULAR TRAIN, ready to work, and absolutely GET AFTER IT. LET'S GO.",
    "Been dealing with some CRAZY STRESS recently. I haven't been myself, but tomorrow's time to FLIP THAT SWITCH. It's FRIDAY. Best day of the week. LET'S GET AFTER IT, people.",
    "It's 12 AM on MONDAY morning. LET'S RALLY and HAVE A WEEK, people. These vocal cords are absolutely SHREDDED. Doesn't matter. I'm gonna be back. READY TO ROCK.",
    "Run the ball until they stop us. KEEP POUNDING out the content. They all know what's coming. They CAN'T KEEP UP with the speed. LET'S GO, people.",
    "When that ALARM CLOCK goes off, I'm OFF. From there, I'm going right into a WORKOUT.",
    "I WILL BE starting a company to deliver the products that the people want.",
    "I'm TIRED this morning just like everyone else, but it's TIME to LOCK IN because we have a job to do. ONE TEAM GETTING AFTER IT on a MONDAY.",
    "Never really cared about social media, and that's why you'll see me continue to PUMP the ALGORITHM with some CRAZY CONTENT.",
    "Young people are MOTIVATED to put an extra WORK on SUNDAYS and be responsible. Hey. That's a quote you're NOT gonna find in the mainstream media. LET'S KEEP proving it TRUE.",
    "Everyone has a PURPOSE and is on this planet for a reason. KEEP BELIEVING in yourself because I know we're gonna find our past day by day.",
    "Big ENERGY going into the EARLY MORNING WORKOUT because I'm about to get AFTER IT for my family, friends, and everyone who cares about me. God make the most of EVERY DAY. Big things are gonna happen. LET'S GO, people.",
    "RISER MODE. Wake up early, get a workout in, and get AFTER IT at work to RISE UP in the community. LET'S GO, people. LOCKED IN. Make it happen.",
    "Still SICK AS A DOG on this FRIDAY, hammering the WORK FROM HOME trying to make things happen.",
    "Sending POSITIVE VIBES and GOOD ENERGY to everyone. LET'S have a DAY, people.",
    "Who's GETTING AFTER IT on a FRIDAY AFTERNOON?",
    "I like my 9 to 5 job because it allows me to HELP the COMMUNITY and keep everyone's money safe. I specifically picked it out because I get to learn from GREAT PEOPLE every day.",
    "I always tell my family that I LOVE THEM, and I make sure I give them HUGS because I never know what day is gonna be my LAST. Whether it comes a 100 minutes or a 100 years from now, I'm gonna make sure I take care of the people who I care about. I'm gonna live EVERY DAY to the FULLEST.",
    "We are ABSOLUTELY ON IT. READY TO RIP on this beautiful MONDAY MORNING. LET'S have a DAY, people.",
    "It's all about GOING AFTER IT every day and WORKING HARD.",
    "I might be the BEST DRESSED person WORKING FROM HOME in America today because I care about what I'm doing. I wanna represent the qualities that I care about. If you've got a better fit, let me see it and prove me wrong. It's all about pushing everyone to NEW HEIGHTS.",
    "Please carry the AMERICAN ECONOMY for me because I got wicked SICK today. I got full 45 minutes of sleep this afternoon, but I still only managed 85 Etch A Sketches. Tough one, and we're gonna need some HELP.",
    "Just CRUISING around, there are some ABSOLUTE CHARACTERS out here..."
];

export const allVideos = [
    'shit my pants like crazy.mp4',
    'until the breaks give out, lets ride people.mp4',
    'whoever lives the truth comes ot the light.mp4',
    'Come after Me.mp4',
    'I_m not an influencer.mp4',
    'running on fumes - lets get it locked in today.mp4',
    'haven_t been feeling myself today.mp4',
    'when opportunity knocks - friday.mp4',
    'sleep in at least 1 day a week.mp4',
    'back on the regular train, ready to get after it.mp4',
    'I like my 9-5 job.mp4',
    'Became an overnight sensation through hardwork.mp4',
    'hammered weights on a saturday.mp4',
    'competative world .mp4',
    'Locked in for greatness today.mp4',
    'absolute characters out here.mp4',
    'apologise to absolutely nobody.mp4',
    'We need the communitys help.mp4',
    'Yo - We are absolutely locked in!.mp4',
    '12 hours of sleep time to rip again.mp4',
    'Crushed 5 burritos.mp4',
    'amost monday people.mp4',
    'Best fit in america - prove me wrong.mp4',
    'who are you inspiring.mp4',
    'never cared about social media - pump algo.mp4',
    'Fun Work day.mp4',
    'favourite hobbies - working out and studying.mp4',
    'I_m still hungry.mp4',
    'got to make the most of every day.mp4',
    'locked in to the absolute max.mp4',
    'havy hitters watch out.mp4',
    'When that alarm clock goes off.mp4',
    'nerves through the roof this week.mp4',
    'Be respectfull of everyone else .mp4',
    'Im not locked in, SIYC.mp4',
    'make sure you_re right then go ahead.mp4',
    'Diversifying my business persuits.mp4',
    'heavy hitters about to be shaking in their boots.mp4',
    'you will not catch me slacking today.mp4',
    'Overnight Sensation.mp4',
    'fridays are for the heaby hitters.mp4',
    'Thank you for your sacrifice.mp4',
    'Sunday lock in .mp4',
    'Music intro.mp4',
    'I_m not selling out.mp4',
    'The US is the greates country on earth.mp4',
    'the hate fuels me.mp4',
    'share your opinions - greatest country on earth.mp4',
    'just a normal dude getting after it - long week.mp4',
    'difficulty getting workouts in.mp4',
    'sunday positive vibes.mp4',
    'still sick as a dog on this friday.mp4',
    'keep pumping the content.mp4',
    'it_s all about going after it every day.mp4',
    'gunna need a big second half of the day.mp4',
    'The heavy hitters haven_t seen a rise this fast.mp4',
    'hauling it through a downpour today.mp4',
    'Ispire america.mp4',
    'never know what day will be your last.mp4',
    'dailed in.mp4',
    'chef_ed up a bowl of bison.mp4',
    'they aren_t ready - we are coming.mp4',
    'time to lock back in.mp4',
    'Change is hard.mp4',
    'riser morning workout.mp4',
    'young people work on sundays.mp4',
    'Absolutely locked in!.mp4',
    'who_s getting after it on a friday afternoon.mp4',
    'rabble rousers fired up .mp4',
    'riser mode.mp4',
    'make fun of me - america.mp4',
    'Nvidia can_t keep up.mp4',
    'lcoked in working from home.mp4',
    'Carry the American Economy.mp4',
    'help others core values.mp4',
    'hird better chirps at the duck pond.mp4',
    'you don_t go where the puck is.mp4',
    'I_m tired but time to lock in - monday.mp4',
    'I will be starting a company.mp4',
    'its 12am on monday morining.mp4',
    '9 to 5 job, no sunday scaries.mp4',
    'everyone has a purpose.mp4',
    'Ok, it_s a set back.mp4',
    'We are absolutely locked in!.mp4',
    'gotta be responsible - friday night.mp4',
    'ready to rip - monday morning .mp4',
    'some men cant be bought.mp4'
];
